### ISSUE TITLE
Plugins don't work with UE4.17

### ISSUE THREAD

**Issue by Sleepy-Pete** [n1ckfg/drawing_methods#1]
Can't open project.

**Comment by n1ckfg** [comment]
What OS? Tested on UE 4.17, Windows 10 and Ubuntu 16. Remember to set up a new Unreal project before building it by right-clicking and choosing Generate Project Files (Win) or running the GenerateProjectFiles.sh script (Linux)

**Comment by Sleepy-Pete** [comment]
I'm sorry I should have come back to adjust this comment. My visual studio might be the cause of my problem. Let me continue to work it out and I'll get back to you and try your method properly.

**Comment by Sleepy-Pete** [comment]
So I'm currently running it on Windows 10 and it telling me RuntimeMeshComponent plugin is not compatible with 4.17. After it asks me to rebuild the .dll of drawing which fails and states it can't be compiled and I should try rebuilding them manually which I have tried. I also started this process by generating project files.

**Comment by n1ckfg** [comment]
Try regenerating project files, opening the sln file in VS 2017, and building the plugins there. Then open the uproject in Unreal.

**Comment by Sleepy-Pete** [comment]
Thank you for having patience with me. After repairing my VS 2017, double checking all the components I needed, and rebuilding the solution the project started up. Thanks for your assistance and for the project.
